'use client';

import { useState } from 'react';
import { useFirestore } from '@/firebase/provider';
import { useCollection } from '@/firebase/firestore/use-collection';
import { useUser } from '@/firebase/auth/use-user';
import { collection, query, orderBy } from 'firebase/firestore';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import type { TrainingModule, UserRole } from '@/lib/types';
import { BookOpen, Video, Users, CheckCircle, Clock } from 'lucide-react';

export default function TrainingPage() {
  const { db } = useFirestore();
  const { user } = useUser();
  const { toast } = useToast();

  const modulesQuery = query(collection(db, 'training_modules'), orderBy('createdAt', 'desc'));
  const { data: modules = [], loading } = useCollection<TrainingModule>(modulesQuery);

  const activeModules = modules.filter(m => m.status === 'Active');
  const draftModules = modules.filter(m => m.status === 'Draft');

  const getFormatIcon = (format: TrainingModule['format']) => {
    switch (format) {
      case 'Video':
        return <Video className="h-4 w-4" />;
      case 'In-Person':
        return <Users className="h-4 w-4" />;
      case 'Live Online':
        return <Users className="h-4 w-4" />;
      default:
        return <BookOpen className="h-4 w-4" />;
    }
  };

  const getFormatBadgeColor = (format: TrainingModule['format']) => {
    const colors: Record<TrainingModule['format'], string> = {
      'In-Person': 'bg-blue-100 text-blue-800',
      'Live Online': 'bg-green-100 text-green-800',
      'Video': 'bg-purple-100 text-purple-800',
      'Interactive': 'bg-orange-100 text-orange-800',
      'Reading': 'bg-gray-100 text-gray-800',
    };
    return colors[format];
  };

  return (
    <div className="p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Training Modules</h1>
        <p className="text-muted-foreground">
          AI-generated training content for staff development
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-4 mb-8">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Modules</CardTitle>
            <BookOpen className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{modules.length}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{activeModules.length}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">In Draft</CardTitle>
            <Clock className="h-4 w-4 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{draftModules.length}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Avg Completion</CardTitle>
            <Users className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {modules.length > 0
                ? Math.round(modules.reduce((acc, m) => acc + m.completionRate, 0) / modules.length)
                : 0}%
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Training Modules List */}
      <Card>
        <CardHeader>
          <CardTitle>Training Modules</CardTitle>
          <CardDescription>
            Browse and access training materials generated by the Training Agent
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <p>Loading training modules...</p>
          ) : modules.length === 0 ? (
            <div className="text-center py-8">
              <BookOpen className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
              <p className="text-muted-foreground mb-4">
                No training modules yet. The Training Agent will create modules as needed.
              </p>
            </div>
          ) : (
            <div className="grid gap-4 md:grid-cols-2">
              {modules.map(module => (
                <div key={module.id} className="border rounded-lg p-4 hover:shadow-md transition-shadow">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1">
                      <h3 className="font-semibold text-lg mb-1">{module.title}</h3>
                      <p className="text-sm text-muted-foreground mb-2">{module.description}</p>
                    </div>
                    {getFormatIcon(module.format)}
                  </div>

                  <div className="flex flex-wrap gap-2 mb-3">
                    <Badge className={getFormatBadgeColor(module.format)}>{module.format}</Badge>
                    <Badge variant={module.status === 'Active' ? 'default' : 'secondary'}>
                      {module.status}
                    </Badge>
                    <Badge variant="outline">{module.duration} min</Badge>
                  </div>

                  <div className="mb-3">
                    <div className="text-xs text-muted-foreground mb-1">Target Roles:</div>
                    <div className="flex flex-wrap gap-1">
                      {module.targetRoles.map((role, idx) => (
                        <Badge key={idx} variant="outline" className="text-xs">
                          {role}
                        </Badge>
                      ))}
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t">
                    <div className="text-sm">
                      <span className="text-muted-foreground">Completion: </span>
                      <span className="font-medium">{module.completionRate}%</span>
                    </div>
                    <Button size="sm" variant="outline">View Module</Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
